# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='bm_proto.proto',
  package='bm_proto',
  serialized_pb='\n\x0e\x62m_proto.proto\x12\x08\x62m_proto\"o\n\x08\x45nvelope\x12\x11\n\tclient_id\x18\x01 \x01(\r\x12\x12\n\nmessage_id\x18\x02 \x01(\r\x12+\n\x0cmessage_type\x18\x03 \x01(\x0e\x32\x15.bm_proto.MessageType\x12\x0f\n\x07payload\x18\x04 \x03(\x0c\"1\n\x05Vec3f\x12\x0c\n\x01x\x18\x01 \x01(\x02:\x01\x30\x12\x0c\n\x01y\x18\x02 \x01(\x02:\x01\x30\x12\x0c\n\x01z\x18\x03 \x01(\x02:\x01\x30\"q\n\x08Position\x12\x11\n\tgalaxy_id\x18\x01 \x01(\r\x12\x11\n\tsystem_id\x18\x02 \x01(\r\x12\x16\n\x0e\x64\x65stination_id\x18\x03 \x01(\r\x12\'\n\x0elocal_position\x18\x04 \x01(\x0b\x32\x0f.bm_proto.Vec3f\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1b\n\x0b\x43hatMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\"4\n\x12PrivateChatMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"!\n\x11ServerChatMessage\x12\x0c\n\x04text\x18\x01 \x01(\t*b\n\x0bMessageType\x12\x0e\n\nUSER_LOGIN\x10\x64\x12\x10\n\x0c\x43HAT_MESSAGE\x10\x65\x12\x18\n\x14PRIVATE_CHAT_MESSAGE\x10\x66\x12\x17\n\x13SERVER_CHAT_MESSAGE\x10g')

_MESSAGETYPE = descriptor.EnumDescriptor(
  name='MessageType',
  full_name='bm_proto.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='USER_LOGIN', index=0, number=100,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CHAT_MESSAGE', index=1, number=101,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PRIVATE_CHAT_MESSAGE', index=2, number=102,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SERVER_CHAT_MESSAGE', index=3, number=103,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=477,
  serialized_end=575,
)


USER_LOGIN = 100
CHAT_MESSAGE = 101
PRIVATE_CHAT_MESSAGE = 102
SERVER_CHAT_MESSAGE = 103



_ENVELOPE = descriptor.Descriptor(
  name='Envelope',
  full_name='bm_proto.Envelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='client_id', full_name='bm_proto.Envelope.client_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message_id', full_name='bm_proto.Envelope.message_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message_type', full_name='bm_proto.Envelope.message_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload', full_name='bm_proto.Envelope.payload', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=139,
)


_VEC3F = descriptor.Descriptor(
  name='Vec3f',
  full_name='bm_proto.Vec3f',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='bm_proto.Vec3f.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='bm_proto.Vec3f.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='z', full_name='bm_proto.Vec3f.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=141,
  serialized_end=190,
)


_POSITION = descriptor.Descriptor(
  name='Position',
  full_name='bm_proto.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='galaxy_id', full_name='bm_proto.Position.galaxy_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='system_id', full_name='bm_proto.Position.system_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='destination_id', full_name='bm_proto.Position.destination_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='local_position', full_name='bm_proto.Position.local_position', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=192,
  serialized_end=305,
)


_LOGINREQUEST = descriptor.Descriptor(
  name='LoginRequest',
  full_name='bm_proto.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='username', full_name='bm_proto.LoginRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password', full_name='bm_proto.LoginRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=307,
  serialized_end=357,
)


_CHATMESSAGE = descriptor.Descriptor(
  name='ChatMessage',
  full_name='bm_proto.ChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='bm_proto.ChatMessage.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=359,
  serialized_end=386,
)


_PRIVATECHATMESSAGE = descriptor.Descriptor(
  name='PrivateChatMessage',
  full_name='bm_proto.PrivateChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='bm_proto.PrivateChatMessage.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='username', full_name='bm_proto.PrivateChatMessage.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=388,
  serialized_end=440,
)


_SERVERCHATMESSAGE = descriptor.Descriptor(
  name='ServerChatMessage',
  full_name='bm_proto.ServerChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='bm_proto.ServerChatMessage.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=442,
  serialized_end=475,
)

_ENVELOPE.fields_by_name['message_type'].enum_type = _MESSAGETYPE
_POSITION.fields_by_name['local_position'].message_type = _VEC3F
DESCRIPTOR.message_types_by_name['Envelope'] = _ENVELOPE
DESCRIPTOR.message_types_by_name['Vec3f'] = _VEC3F
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['ChatMessage'] = _CHATMESSAGE
DESCRIPTOR.message_types_by_name['PrivateChatMessage'] = _PRIVATECHATMESSAGE
DESCRIPTOR.message_types_by_name['ServerChatMessage'] = _SERVERCHATMESSAGE

class Envelope(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENVELOPE
  
  # @@protoc_insertion_point(class_scope:bm_proto.Envelope)

class Vec3f(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VEC3F
  
  # @@protoc_insertion_point(class_scope:bm_proto.Vec3f)

class Position(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POSITION
  
  # @@protoc_insertion_point(class_scope:bm_proto.Position)

class LoginRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGINREQUEST
  
  # @@protoc_insertion_point(class_scope:bm_proto.LoginRequest)

class ChatMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHATMESSAGE
  
  # @@protoc_insertion_point(class_scope:bm_proto.ChatMessage)

class PrivateChatMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PRIVATECHATMESSAGE
  
  # @@protoc_insertion_point(class_scope:bm_proto.PrivateChatMessage)

class ServerChatMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVERCHATMESSAGE
  
  # @@protoc_insertion_point(class_scope:bm_proto.ServerChatMessage)

# @@protoc_insertion_point(module_scope)
