#!/usr/bin/env python

import logging
import logging.config
import time
import bm_user.service
import bm_user.store
import bm_shared.rpc

LOG = logging.getLogger(__name__)


def main():
    logging.config.fileConfig('logging.conf', disable_existing_loggers=False)

    try:
        LOG.info('Bootstrapping server')
        server = bm_shared.rpc.RPCServer()

        LOG.info('Initializing database')
        user_store = bm_user.store.UserStore()

        #user_store.first_run()
        #user_store.add_user('fpj', 'fpj', 'fpj@fpj.com')

        LOG.info('Initializing RPC service')
        user_service = bm_user.service.UserService(user_store)

        server.add_service(user_service)

        LOG.info('Starting server')
        server.start_server(8080)

        LOG.info('Entering main loop')
        while True:
            server.read_from_clients()
            server.accept_pending_clients()
            server.write_to_clients()
            time.sleep(0.1)

    except Exception:
        LOG.exception('Server crashed :-(')

    except KeyboardInterrupt:
        LOG.info('Keyboard interrupt')

    finally:
        server.stop_server()
        user_store.close()


if __name__ == '__main__':
    main()
