
# default desktop
DEFAULT_DESKTOP_SCREEN_WIDTH = 1024
DEFAULT_DESKTOP_SCREEN_HEIGHT = 768

# landscape mode
IPHONE_4_SCREEN_WIDTH = 960
IPHONE_4_SCREEN_HEIGHT = 640

# landscape mode
IPHONE_5_SCREEN_WIDTH = 1136
IPHONE_5_SCREEN_HEIGHT = 640
